/* Form definition file generated by fdesign on Wed Apr 11 13:12:11 2018 */

#include <stdlib.h>
#include "jcamsysxarchive_form_main.h"

#include "jcamsys.h"
#include "jcamsysxarchive.h"
#include "jcamsysxarchive_form_archive2.h"



/***************************************


 ***************************************/

extern FD_archive   *fd_archive;
extern int app_width;
extern int app_height;

void timer_cb (FL_OBJECT* obj, long data );

FD_main *
create_form_main( void )
{
    	FL_OBJECT *obj;
    	FD_main *fdui = ( FD_main * ) fl_malloc( sizeof *fdui );

    	fdui->vdata = fdui->cdata = NULL;
    	fdui->ldata = 0;

    	fdui->main  = fl_bgn_form( FL_NO_BOX, app_width, app_height );

    	//obj = fl_add_box( FL_FLAT_BOX, 0, 0, 641, 523, "" );
    	//fl_set_object_color( obj, FL_BLACK, FL_BLACK );

        fdui->tabs = obj = fl_add_tabfolder(FL_TOP_TABFOLDER,0,0,JC_MAX_WIDTH+JC_PLUSX,JC_MAX_HEIGHT+JC_PLUSY,"");
	fl_set_object_boxtype( obj, FL_NO_BOX );
    	fl_set_object_color( obj, FL_BLACK, FL_BLACK );
    	fl_set_object_lcolor( obj, FL_WHITE );
    	fl_set_object_callback( obj, tabs_cb, 0 );

        fl_addto_tabfolder(obj,"ARCHIVE",fd_archive->archive);
        //fl_addto_tabfolder(obj,"CAMERA-SETTINGS",fd_camerasettings->camerasettings);

	fdui->tim = obj = fl_add_timer( FL_HIDDEN_TIMER, 0, 0, 27, 27, "timer" );
    	fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    	fl_set_object_callback( obj, timer_cb, 0 );

    	fl_end_form( );
    	fdui->main->fdui = fdui;
    	return fdui;
}



