/* Header file generated by fdesign on Sun Apr 29 11:59:13 2018 */

#ifndef FD_archive_h_
#define FD_archive_h_

#include <forms.h>

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */



/* Forms and Objects */

typedef struct {
    FL_FORM   * archive;
    void      * vdata;
    char      * cdata;
    long        ldata;
} FD_archive;

FD_archive * create_form_archive( void );

#if defined __cplusplus
}
#endif

#endif /* FD_archive_h_ */
