/* Form definition file generated by fdesign on Sun Apr 29 11:59:13 2018 */

#include <stdlib.h>
#include "jcamsysxarchive_form_archive2.h"


/***************************************
 ***************************************/

FD_archive *
create_form_archive( void )
{
    FL_OBJECT *obj;
    FD_archive *fdui = ( FD_archive * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->archive = fl_bgn_form( FL_NO_BOX, 1024, 716 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 1024, 716, "" );

    obj = fl_add_box( FL_UP_BOX, -1, -1, 1025, 717, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLACK );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 320, 720, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 60, 490, 210, 20, "Su   Mo   Tu   We   Th    Fr   Sa" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 60, 520, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 90, 520, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 120, 520, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 150, 520, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 180, 520, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 210, 520, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 240, 520, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 90, 560, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 120, 560, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 150, 560, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 180, 560, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 210, 560, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 240, 560, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 60, 560, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 60, 600, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 90, 600, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 120, 600, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 150, 600, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 180, 600, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 210, 600, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 240, 600, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 60, 640, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 90, 640, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 120, 640, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 150, 640, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 180, 640, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 210, 640, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 240, 640, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 60, 680, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 90, 680, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 120, 680, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 150, 680, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 180, 680, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 210, 680, 20, 30, "88" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 240, 680, 20, 30, "88" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 20, 560, 30, 110, "" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 270, 560, 30, 110, "" );

    obj = fl_add_spinner( FL_INT_SPINNER, 170, 460, 60, 30, "" );
    fl_set_spinner_bounds( obj, 2010, 3000 );
    fl_set_spinner_value( obj, 2010 );

    obj = fl_add_text( FL_NORMAL_TEXT, 100, 460, 60, 30, "Month" );

    obj = fl_add_canvas( FL_NORMAL_CANVAS, 330, 0, 690, 550, "" );

    obj = fl_add_slider( FL_HOR_BROWSER_SLIDER, 10, 400, 300, 30, "Hour" );
    fl_set_object_lsize( obj, FL_DEFAULT_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_return( obj, FL_RETURN_CHANGED );
    fl_set_slider_bounds( obj, 0, 23 );
    fl_set_slider_value( obj, 0 );
    fl_set_slider_step( obj, 1 );
    fl_set_slider_increment( obj, 1, 1 );

    obj = fl_add_slider( FL_HOR_BROWSER_SLIDER, 10, 330, 300, 30, "Min" );
    fl_set_object_lsize( obj, FL_DEFAULT_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_return( obj, FL_RETURN_CHANGED );
    fl_set_slider_bounds( obj, 0, 59 );
    fl_set_slider_value( obj, 0 );
    fl_set_slider_step( obj, 1 );
    fl_set_slider_increment( obj, 1, 1 );

    obj = fl_add_bitmapbutton( FL_NORMAL_BUTTON, 700, 610, 80, 60, "PLAY" );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );

    obj = fl_add_bitmapbutton( FL_NORMAL_BUTTON, 550, 610, 80, 60, "PAUSE" );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );

    obj = fl_add_text( FL_NORMAL_TEXT, 330, 560, 690, 20, "Filename" );

    obj = fl_add_slider( FL_HOR_BROWSER_SLIDER, 340, 680, 670, 20, "" );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fl_end_form( );

    fdui->archive->fdui = fdui;

    return fdui;
}
