/* Header file generated by fdesign on Wed Apr 11 12:29:27 2018 */

#ifndef FD_form0_h_
#define FD_form0_h_

#include  "include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void button_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * form0;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * br;
} FD_form0;

FD_form0 * create_form_form0( void );

#if defined __cplusplus
}
#endif

#endif /* FD_form0_h_ */
