/* Header file generated by fdesign on Wed Apr 11 12:29:51 2018 */

#ifndef FD_ttt_h_
#define FD_ttt_h_

#include  "include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void done( FL_OBJECT *, long );
void reload( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * ttt;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * bm;
    FL_OBJECT * pm;
    FL_OBJECT * done;
    FL_OBJECT * load;
} FD_ttt;

FD_ttt * create_form_ttt( void );

#if defined __cplusplus
}
#endif

#endif /* FD_ttt_h_ */
