/* Header file generated by fdesign on Tue Apr 10 06:37:47 2018 */

#ifndef FD_cameraview_h_
#define FD_cameraview_h_

#include <forms.h>

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void camchange( FL_OBJECT *, long );
void timer_cb( FL_OBJECT *, long );
void changesize( FL_OBJECT *, long );
void newme( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * cameraview;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * largeviewcanvas;
    FL_OBJECT * bcam1;
    FL_OBJECT * bcam2;
    FL_OBJECT * bcam3;
    FL_OBJECT * bcam4;
    FL_OBJECT * bcam5;
    FL_OBJECT * bcam6;
    FL_OBJECT * bcam7;
    FL_OBJECT * bcam8;
    FL_OBJECT * bcam9;
    FL_OBJECT * tim;
    FL_OBJECT * textbox;
    FL_OBJECT * bcam10;
    FL_OBJECT * btnsize;
    FL_OBJECT * newviewer;
} FD_cameraview;

FD_cameraview * create_form_cameraview( void );

#if defined __cplusplus
}
#endif

#endif /* FD_cameraview_h_ */
