/* Form definition file generated by fdesign on Tue Apr 10 06:37:47 2018 */

#include <stdlib.h>
#include "jcamsysxviewer_form.h"


/***************************************
 ***************************************/

FD_cameraview *
create_form_cameraview( void )
{
    FL_OBJECT *obj;
    FD_cameraview *fdui = ( FD_cameraview * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->cameraview = fl_bgn_form( FL_NO_BOX, 641, 523 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 641, 523, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLACK );

    fdui->largeviewcanvas = obj = fl_add_bitmap( FL_NORMAL_BITMAP, 0, 0, 639, 486, "" );

    fdui->bcam1 = obj = fl_add_button( FL_NORMAL_BUTTON, 108, 486, 30, 30, "1" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 1 );

    fdui->bcam2 = obj = fl_add_button( FL_NORMAL_BUTTON, 153, 486, 30, 30, "2" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 2 );

    fdui->bcam3 = obj = fl_add_button( FL_NORMAL_BUTTON, 198, 486, 30, 30, "3" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 3 );

    fdui->bcam4 = obj = fl_add_button( FL_NORMAL_BUTTON, 243, 486, 30, 30, "4" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 4 );

    fdui->bcam5 = obj = fl_add_button( FL_NORMAL_BUTTON, 288, 486, 30, 30, "5" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 5 );

    fdui->bcam6 = obj = fl_add_button( FL_NORMAL_BUTTON, 333, 486, 30, 30, "6" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 6 );

    fdui->bcam7 = obj = fl_add_button( FL_NORMAL_BUTTON, 378, 486, 30, 30, "7" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 7 );

    fdui->bcam8 = obj = fl_add_button( FL_NORMAL_BUTTON, 423, 486, 30, 30, "8" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 8 );

    fdui->bcam9 = obj = fl_add_button( FL_NORMAL_BUTTON, 468, 486, 30, 30, "9" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 9 );

    fdui->tim = obj = fl_add_timer( FL_HIDDEN_TIMER, 0, 0, 27, 27, "timer" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, timer_cb, 0 );

    fdui->textbox = obj = fl_add_text( FL_NORMAL_TEXT, 36, 18, 576, 72, "" );
    fl_set_object_color( obj, FL_BLACK, FL_TOMATO );
    fl_set_object_lcolor( obj, FL_ALICEBLUE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->bcam10 = obj = fl_add_button( FL_NORMAL_BUTTON, 513, 486, 30, 30, "0" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, camchange, 10 );

    fdui->btnsize = obj = fl_add_button( FL_NORMAL_BUTTON, 18, 486, 30, 30, "S" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_DARKCYAN );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, changesize, 1 );

    fdui->newviewer = obj = fl_add_button( FL_NORMAL_BUTTON, 594, 486, 30, 30, "+" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_ALICEBLUE );
    fl_set_object_lcolor( obj, FL_BOTTOM_BCOL );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, newme, 10 );

    fl_end_form( );

    fdui->cameraview->fdui = fdui;

    return fdui;
}
