/* Header file generated by fdesign on Wed Apr 11 14:12:21 2018 */

#ifndef FD_cameraview_h_
#define FD_cameraview_h_

#include <forms.h>

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void camchange( FL_OBJECT *, long );
void timer_cb( FL_OBJECT *, long );
void newme( FL_OBJECT *, long );
//void changesize( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * cameraview;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * largeviewcanvas;
    FL_OBJECT * bcam[JC_MAX_CAMS+1];
    FL_OBJECT * tim;
    FL_OBJECT * textbox;
    FL_OBJECT * bcam10;
    FL_OBJECT * newviewer;
    FL_OBJECT * btnsize;
} FD_cameraview;

FD_cameraview * create_form_cameraview( void );

#if defined __cplusplus
}
#endif

#endif /* FD_cameraview_h_ */
