/* Header file generated by fdesign on Thu Apr 12 07:32:16 2018 */

#ifndef FD_preview9_h_
#define FD_preview9_h_

#include <forms.h>

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void timer_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * preview9;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * tim;
    FL_OBJECT * previewbm[9];
} FD_preview9;

FD_preview9 * create_form_preview9( void );

#if defined __cplusplus
}
#endif

#endif /* FD_preview9_h_ */
