/* Header file generated by fdesign on Wed Apr 11 14:14:06 2018 */

#ifndef FD_main_h_
#define FD_main_h_

#include <forms.h>

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void tabs_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * main;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * tabs;
} FD_main;

FD_main * create_form_main( void );

#if defined __cplusplus
}
#endif

#endif /* FD_main_h_ */
