/* Form definition file generated by fdesign on Thu Apr 12 12:20:45 2018 */

#include <stdlib.h>
#include "jcamsys.h"
#include "jcamsysxviewert.h"
#include "jcamsysxviewert_form_preview4.h"


/***************************************
 ***************************************/

FD_preview4 *
create_form_preview4( void )
{
    FL_OBJECT *obj;
    FD_preview4 *fdui = ( FD_preview4 * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->preview4 = fl_bgn_form( FL_NO_BOX, JC_MAX_WIDTH+JC_PLUSX, JC_MAX_HEIGHT+JC_PLUSY );

    fdui->background = obj = fl_add_box( FL_FLAT_BOX, 0, 0, JC_MAX_WIDTH+JC_PLUSX, JC_MAX_HEIGHT+JC_PLUSY, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_BLACK );

    obj = fl_add_box( FL_UP_BOX, 0, 0, JC_MAX_WIDTH+JC_PLUSX, JC_MAX_HEIGHT+JC_PLUSY, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLACK );

    fdui->tim = obj = fl_add_timer( FL_HIDDEN_TIMER, 0, 0, 27, 27, "timer" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, timer_cb, 0 );

    fdui->previewbm[0] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 0, 0, 324, 252, "" );
fl_set_object_boxtype( obj, FL_NO_BOX );

    fdui->previewbm[1] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 321, 0, 324, 252, "" );
fl_set_object_boxtype( obj, FL_NO_BOX );

    fdui->previewbm[2] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 0, 252, 324, 252, "" );
fl_set_object_boxtype( obj, FL_NO_BOX );

    fdui->previewbm[3] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 321, 252, 324, 252, "" );
fl_set_object_boxtype( obj, FL_NO_BOX );

    fl_end_form( );

    fdui->preview4->fdui = fdui;

    return fdui;
}
