/* Header file generated by fdesign on Thu Apr 12 07:41:18 2018 */

#ifndef FD_sensors_h_
#define FD_sensors_h_

#include <forms.h>

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */



/* Forms and Objects */

typedef struct {
    FL_FORM   * sensors;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * sen_t1;
    FL_OBJECT * sen_t2;
    FL_OBJECT * sen_t3;
    FL_OBJECT * sen_t4;
    FL_OBJECT * sen_t5;
    FL_OBJECT * sen_t6;
} FD_sensors;

FD_sensors * create_form_sensors( void );

#if defined __cplusplus
}
#endif

#endif /* FD_sensors_h_ */
