/* Form definition file generated by fdesign on Thu Apr 12 07:32:16 2018 */

#include <stdlib.h>
#include "jcamsys.h"
#include "jcamsysxviewert.h"
#include "jcamsysxviewert_form_preview9.h"


/***************************************
 ***************************************/

FD_preview9 *
create_form_preview9( void )
{
    FL_OBJECT *obj;
    FD_preview9 *fdui = ( FD_preview9 * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->preview9 = fl_bgn_form( FL_NO_BOX, JC_MAX_WIDTH+JC_PLUSX, JC_MAX_HEIGHT+JC_PLUSY );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, JC_MAX_WIDTH+JC_PLUSX, JC_MAX_HEIGHT+JC_PLUSY, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_BLACK );

    fdui->background = obj = fl_add_box( FL_UP_BOX, 0, 0, JC_MAX_WIDTH+JC_PLUSX, JC_MAX_HEIGHT+JC_PLUSY, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLACK );


    fdui->tim = obj = fl_add_timer( FL_HIDDEN_TIMER, 0, 0, 27, 27, "timer" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, timer_cb, 0 );

    fdui->previewbm[0] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 0, 0, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[1] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 216, 0, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[2] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 429, 0, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[3] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 0, 171, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[4] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 216, 171, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[5] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 429, 171, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[6] = obj = fl_add_canvas( FL_NORMAL_CANVAS,  0, 342, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[7] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 216, 342, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );

    fdui->previewbm[8] = obj = fl_add_canvas( FL_NORMAL_CANVAS, 429, 342, 216, 171, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );


    fl_end_form( );

    fdui->preview9->fdui = fdui;

    return fdui;
}
