/* Form definition file generated by fdesign on Thu Apr 12 07:41:18 2018 */

#include <stdlib.h>
#include "jcamsys.h"
#include "jcamsysxviewert_form_sensors.h"


/***************************************
 ***************************************/

FD_sensors *
create_form_sensors( void )
{
    FL_OBJECT *obj;
    FD_sensors *fdui = ( FD_sensors * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    //fdui->sensors = fl_bgn_form( FL_NO_BOX, 641, 523 );
    fdui->sensors = fl_bgn_form( FL_NO_BOX, JC_MAX_WIDTH+10, JC_MAX_HEIGHT+10 );

    //obj = fl_add_box( FL_FLAT_BOX, 0, 0, 641, 523, "" );
    obj = fl_add_box( FL_FLAT_BOX, 0, 0, JC_MAX_WIDTH+10, JC_MAX_HEIGHT+10, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_BLACK );

    fdui->sen_t1 = obj = fl_add_box( FL_NO_BOX, 90, 45, 459, 45, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_DODGERBLUE );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->sen_t2 = obj = fl_add_box( FL_NO_BOX, 90, 126, 459, 45, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_DODGERBLUE );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->sen_t3 = obj = fl_add_box( FL_NO_BOX, 90, 207, 459, 45, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_DODGERBLUE );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->sen_t4 = obj = fl_add_box( FL_NO_BOX, 90, 288, 459, 45, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_DODGERBLUE );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->sen_t5 = obj = fl_add_box( FL_NO_BOX, 90, 369, 459, 45, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_DODGERBLUE );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->sen_t6 = obj = fl_add_box( FL_NO_BOX, 90, 450, 459, 45, "" );
    fl_set_object_color( obj, FL_DODGERBLUE, FL_DODGERBLUE );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fl_end_form( );

    fdui->sensors->fdui = fdui;

    return fdui;
}
