#!/bin/bash

ARCH=`arch`
DEST="jcamsysxconsole"


#debug
DEBUG='-g -O0'

REL="../../../.."

#Ad in -O3 later
C="gcc -g -O0 -Wall jcamsysxconsole.c jcamsysxconsole_form_main.c jcamsysxconsole_form_camerasettings.c jcamsysxconsole_form_serversettings.c $DEBUG $REL/jcamsys_common/jcamsys_camerasettings.c $REL/jcamsys_common/jcamsys_images.c $REL/jcamsys_common/md5x.c $REL/jcamsys_common/jcamsys_network.c $REL/jcamsys_common/jcamsys_protocol.c $REL/jcamsys_common/jcamsys_cipher.c $REL/jcamsys_common/jcamsys_common.c $REL/jcamsys_common/jcamsys_client_settings.c -I$REL/jcamsys_common -lforms -lflimage -ljpeg -o $DEST"
echo $C
$C

