/* Form definition file generated by fdesign on Sun Apr 22 13:56:10 2018 */

#include <stdlib.h>
#include "jcamsysxconsole_form_serversettings.h"


/***************************************
 ***************************************/

FD_serversettings *
create_form_serversettings( void )
{
    FL_OBJECT *obj;
    FD_serversettings *fdui = ( FD_serversettings * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->serversettings = fl_bgn_form( FL_NO_BOX, 1024, 716 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 1024, 716, "" );

    obj = fl_add_box( FL_UP_BOX, -1, -1, 1025, 717, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLACK );

    obj = fl_add_box( FL_UP_BOX, 20, 10, 990, 310, "" );

    fdui->enable_archiver = obj = fl_add_button( FL_PUSH_BUTTON, 180, 30, 30, 30, "" );
    fl_set_object_color( obj, FL_COL1, FL_CHARTREUSE );
    fl_set_object_callback( obj, enable_archiver_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 40, 30, 120, 30, "Enable Archiver" );

    obj = fl_add_text( FL_NORMAL_TEXT, 40, 270, 150, 30, "Exit on Arhive Error" );

    fdui->exit_on_archive_error = obj = fl_add_button( FL_PUSH_BUTTON, 190, 270, 30, 30, "" );
    fl_set_object_color( obj, FL_COL1, FL_CHARTREUSE );
    fl_set_object_callback( obj, exit_on_archive_error_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 820, 270, 130, 30, "Archiver Verbose" );

    fdui->archive_verbose = obj = fl_add_button( FL_PUSH_BUTTON, 960, 270, 30, 30, "" );
    fl_set_object_color( obj, FL_COL1, FL_CHARTREUSE );
    fl_set_object_callback( obj, archive_verbose_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 40, 80, 150, 30, "Archive rate" );

    fdui->archive_rate_fps = obj = fl_add_valslider( FL_HOR_BROWSER_SLIDER, 360, 80, 260, 30, "FPS" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT );
    fl_set_object_callback( obj, archive_rate_fps_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );
    fl_set_slider_precision( obj, 0 );
    fl_set_slider_bounds( obj, 1, 30 );
    fl_set_slider_value( obj, 1 );
    fl_set_slider_step( obj, 1 );

    fdui->archive_path = obj = fl_add_input( FL_NORMAL_INPUT, 130, 180, 780, 30, "Archive Path" );
    fl_set_object_callback( obj, archive_path_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 40, 130, 280, 30, "Archive ratte when sensor triggered" );

    fdui->sarchive_rate_fps = obj = fl_add_valslider( FL_HOR_BROWSER_SLIDER, 360, 130, 260, 30, "FPS" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT );
    fl_set_object_callback( obj, sarchive_rate_fps_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );
    fl_set_slider_precision( obj, 0 );
    fl_set_slider_bounds( obj, 1, 30 );
    fl_set_slider_value( obj, 1 );
    fl_set_slider_step( obj, 1 );

    fdui->archive_image_size = obj = fl_add_spinner( FL_INT_SPINNER, 900, 30, 70, 50, "" );
    fl_set_object_callback( obj, archive_image_size_cb, 0 );

    fdui->archive_size = obj = fl_add_text( FL_NORMAL_TEXT, 750, 40, 150, 30, "Archive Image size" );

    fdui->resolution = obj = fl_add_text( FL_NORMAL_TEXT, 820, 90, 150, 30, "Resolution" );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->archive_rate_ms = obj = fl_add_text( FL_NORMAL_TEXT, 630, 80, 80, 30, "ms" );

    fdui->sarchive_rate_ms = obj = fl_add_text( FL_NORMAL_TEXT, 630, 130, 80, 30, "ms" );

    fdui->comment = obj = fl_add_text( FL_NORMAL_TEXT, 40, 230, 940, 30, "Arc" );
    fl_set_object_color( obj, FL_COL1, FL_LIGHTER_COL1 );
    fl_set_object_lcolor( obj, FL_BLUE );

    fdui->archiving_ok = obj = fl_add_pixmap( FL_NORMAL_PIXMAP, 750, 100, 60, 50, "" );

    fdui->ssapply = obj = fl_add_button( FL_PUSH_BUTTON, 920, 180, 70, 30, "Apply" );
    fl_set_object_color( obj, FL_COL1, FL_CHARTREUSE );
    fl_set_object_callback( obj, ssapply_cb, 0 );

    obj = fl_add_box( FL_UP_BOX, 20, 350, 990, 350, "" );

    fdui->server_tcp_port = obj = fl_add_input( FL_NORMAL_INPUT, 180, 380, 130, 30, "Server TCP port" );

    fdui->http_server_tcp_port = obj = fl_add_input( FL_NORMAL_INPUT, 180, 440, 130, 30, "HTTP server TCP port" );

    obj = fl_add_text( FL_NORMAL_TEXT, 350, 380, 150, 30, "KX Server TCP port" );

    fdui->docrc = obj = fl_add_button( FL_PUSH_BUTTON, 470, 440, 30, 30, "" );
    fl_set_object_color( obj, FL_COL1, FL_CHARTREUSE );
    fl_set_object_callback( obj, docrc_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 340, 440, 120, 30, "CRC32 Images" );

    fdui->enable_keyexchange = obj = fl_add_button( FL_PUSH_BUTTON, 230, 520, 30, 30, "" );
    fl_set_object_color( obj, FL_COL1, FL_CHARTREUSE );
    fl_set_object_callback( obj, enable_kx_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 60, 520, 130, 30, "Enable KX Server" );

    fdui->enable_http = obj = fl_add_button( FL_PUSH_BUTTON, 230, 570, 30, 30, "" );
    fl_set_object_color( obj, FL_COL1, FL_CHARTREUSE );
    fl_set_object_callback( obj, enable_http_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 50, 570, 150, 30, "Enable HTTP Server" );

    fl_end_form( );

    fdui->serversettings->fdui = fdui;

    return fdui;
}
